controller_manager:
  ros__parameters:
    update_rate: 500
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    tmr_steering_controller:
      type: forward_command_controller/ForwardCommandController
    tmr_drive_controller:
      type: forward_command_controller/ForwardCommandController
    spine_controller:
      type: position_controllers/JointGroupPositionController

left_arm_controller:
  ros__parameters:
    joints: [left_fr3v2_1_joint1, left_fr3v2_1_joint2, left_fr3v2_1_joint3,
             left_fr3v2_1_joint4, left_fr3v2_1_joint5, left_fr3v2_1_joint6,
             left_fr3v2_1_joint7]
    command_interfaces: [position]
    state_interfaces: [position, velocity]

right_arm_controller:
  ros__parameters:
    joints: [right_fr3v2_1_joint1, right_fr3v2_1_joint2, right_fr3v2_1_joint3,
             right_fr3v2_1_joint4, right_fr3v2_1_joint5, right_fr3v2_1_joint6,
             right_fr3v2_1_joint7]
    command_interfaces: [position]
    state_interfaces: [position, velocity]

tmr_steering_controller:
  ros__parameters:
    joints: [tmrv0_2_joint_0, tmrv0_2_joint_2]
    interface_name: position

tmr_drive_controller:
  ros__parameters:
    joints: [tmrv0_2_joint_1, tmrv0_2_joint_3]
    interface_name: velocity

spine_controller:
  ros__parameters:
    joints: [franka_spine_vertical_joint]

imu_broadcaster:
  ros__parameters:
    sensor_name: imu
    frame_id: imu_imu_sensor_frame
